- hosts: master
  become: yes
  become_method: sudo
  tasks:
    - name: Installing useful packages
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - vim
        - wget
        - elinks
        - telnet
        - bind-utils

    - name: Initialize Kubernetes cluster
      shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt"
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: "{{user}}"
      file:
        path: /home/"{{user}}"/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/"{{user}}"/.kube/config
        remote_src: yes
        owner: centos

    - name: install Pod network
      become: yes
      become_user: "{{user}}"
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
  
  
