- hosts: master
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - name: get join command
      shell: 'kubeadm token create --print-join-command'
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['k8s-master-0'].join_command }} --ignore-preflight-errors all  >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt